spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/serveping
    username: root
    password:

  flyway:
    enabled: true
    validate-on-migrate: true
  jpa:
    show-sql: true
jwt:
  secret: 
